[[pages]]
path = "/workspaces/codespaces-blank/my-spotify-wrapped/my_pages/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Analysis options"
icon = "ğŸ¯"
is_section = true

[[pages]]
path = "/workspaces/codespaces-blank/my-spotify-wrapped/my_pages/release_year.py"
name = "Release year"
icon = "â³"

[[pages]]
path = "/workspaces/codespaces-blank/my-spotify-wrapped/my_pages/most_listened_artists.py"
name = "Most listened artists"
icon = "ğŸ¤"

[[pages]]
path = "/workspaces/codespaces-blank/my-spotify-wrapped/my_pages/listening_habits.py"
name = "Listening habits"
icon = "ğŸ§"

[[pages]]
path = "/workspaces/codespaces-blank/my-spotify-wrapped/my_pages/popularity.py"
name = "Popularity"
icon = "âœ¨"